stages:
  - vet
  - lint
  - build
  - security
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - build/

copyright:
  stage: vet
  script:
    - .scripts/check-notice-authors.sh origin/master
    - .scripts/check-copyright-notice.sh

solium:
  image: node:12
  stage: lint
  before_script:
    - npm install -g ethlint
  script:
    - solium -d contracts/
  allow_failure: false

solhint:
  image: node:12
  stage: lint
  before_script:
    - npm install -g solhint
  script:
    - solhint "contracts/**/*.sol"
  allow_failure: false

build:
  image: node:12
  stage: build
  script:
    - yarn global add truffle typescript
    - yarn install --pure-lockfile
    - yarn build
    - yarn test
  allow_failure: false

coverage:
  image: node:12
  stage: security
  script:
    - yarn global add truffle typescript
    - yarn install --pure-lockfile
    - yarn build
    - yarn run solidity-coverage
  allow_failure: true


mythril:
  image: python:3.7
  stage: security
  before_script:
    - pip3 install mythril
  script:
    - myth truffle
  only:
    changes:
        - contracts/*
  allow_failure: false
